version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: sales_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sales_inventory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: sales_api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024 # Le da 1GB de "aire" a Node
    deploy:
      resources:
        limits:
          memory: 1536M # Límite físico del contenedor
    env_file:
      - .env
    depends_on:
      - postgres_db

  n8n:
    image: n8nio/n8n:latest
    container_name: sales_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres_db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n_db
      DB_POSTGRESDB_USER: admin
      DB_POSTGRESDB_PASSWORD: password123
      EXECUTIONS_DATA_PRUNE: true
      EXECUTIONS_DATA_MAX_AGE: 1
      N8N_METRICS: false
      N8N_EXECUTION_MODE: regular
      N8N_CONCURRENCY_PRODUCTION_LIMIT: 1
    deploy:
      resources:
        limits:
          memory: 2048M # n8n necesita su propio espacio para no chocar con la API
    depends_on:
      - postgres_db
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  pgdata:
  n8n_data:
